### ISSUE TITLE
Can the model work beyond the 5000 diseases?

### ISSUE THREAD

**Issue by hzhz2020** [chaoyi-wu/RadFM#14]
Dear Author

Thanks for the exciting work! It's amazing that the model has been trained on and thus might cover over 5000 diseases. I am wondering, since your goal is building a generalist foundation model for radiology, does the model work beyond the 5000 diseases that it is trained on? 

For example, i work with a heart disease that is diagnose via ultrasound (which is a modality covered in your model). Can i ask the diagnosis question about this disease to the model? 

Thanks!

**Comment by chaoyi-wu** [comment]
It depends. Please check  our latest version paper where we test the generality on PadChest to see how model will work on unseen diseases classes. For some diseases it works but some are just random guessing.  But, in general, I have to acknowledge that  the zero-shot performance on unseen classes is not so promising, especially compared with the specifically trained diagnosis models, I tend to recommend you to view our model as a pre-trained backbone more instead of  using it as a zero-shot generative model in this unseen case.

**Comment by hzhz2020** [comment]
Dear Author

Thank you for your prompt reply, what you said make sense! 
Looking forward to more of the exciting work on this space!
