### ISSUE TITLE
It looks like transformers==4.28.1 will introduce weird output

### ISSUE THREAD

**Issue by Ashespt** [chaoyi-wu/RadFM#27]
Thanks for your great job! Compared to some works I reproduced, this repo's result looks convinced. But, I met some problems during training with transformers==4.28.1. The situation is that the correct result is produced in  transformers==4.28.0.dev0-py3.9.egg while 4.28.1 will come out weird output.
**for 4.28.0.dev0-py3.9.egg**
![image](https://github.com/chaoyi-wu/RadFM/assets/31787778/39aa7855-dad7-4139-96aa-347717409f9e)
**for 4.28.1**
![815c519ba73259568a95a42cbad533f](https://github.com/chaoyi-wu/RadFM/assets/31787778/ba26723a-cd3e-4664-881b-7dec8a8fdf3f)
However, if I used 4.28.0.dev0-py3.9.egg , it will throw errors like

**ImportError: cannot import name 'strtobool' from 'transformers.utils'** 

Do you have any idea about this weird output or dependence? Thanks.

**Comment by chaoyi-wu** [comment]
The issue seems about the language model, i.e. the language model PMC-LLaMA is trained under the 4.28.0.dev0-py3.9.egg version. You'd better check the prompt files to pick a perfect prompt to perform the report generation task, as listed in https://github.com/chaoyi-wu/RadFM/blob/main/src/Dataset/dataset/report_prompt.json.

We are also under checking why the transformers version changes will make the LM so sensitivity to prompts. 

Hope this can help you.
